local blasphemy = Difficulty.new("BLASPHEMY")
blasphemy.displayName = "BLASPHEMY"
blasphemy.icon = Sprite.load("difBlasphemy", "resources/Misc/Sprites/difBlasphemy", 3, 13, 11)
blasphemy.scale = 0.3
blasphemy.scaleOnline = 0.033
local colorBlasphemy = tostring(Color.fromHex(0xCCAE5B).gml)
blasphemy.description = "&"..colorBlasphemy.."&-BLASPHEMY-&!&\nOUR KING, OUR KNIGHT,\n\nOUR SAVIOR, OUR LEADER\n\nTHE LEADER OF THE &"..colorBlasphemy.."&DIVINE!&!&"
blasphemy.forceHardElites = true
blasphemy.enableBlightedEnemies = true
blasphemy.enableMissileIndicators = false
